# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 as builder

WORKDIR /workspace
COPY . .

# build promu
RUN cd promu && go build -mod=mod -o /cachi2/output/deps/gomod/bin/promu

RUN make -f Makefile.dynamic common-build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/memcached_exporter /bin/memcached_exporter

USER       nobody
ENTRYPOINT ["/bin/memcached_exporter"]
EXPOSE     9150
